### PR TITLE
Quiz time beginners. 0

### PR DESCRIPTION
**Pull request by Pixels123priyal**
QuizTime_Beginners.0

### CODE REVIEW

**Comment by Pixels123priyal** [comment]
Please merge our request ... QuizTime_Beginners.0

**Comment by pri1311** [comment]
> Please merge our request ... QuizTime_Beginners.0

@Pixels123priyal images/screenshots are not visible. Please update the readme.

**Comment by pri1311** [comment]
@Pixels123priyal 
image
Still not visible.

**Comment by Pixels123priyal** [comment]
I have updated.. Can you please check once again?

**Pull request merged**
